@extends('layouts.app_content')

@section('content')
<div id="home">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 mb-4">

                <h3 class="mb-5">ShepherdCares.com Privacy Statement</h3>
                
                
                <p style=''><span style="">Updated August 1, 2021</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><span style="">Welcome to the ShepherdCares web site, available at&nbsp;</span><span style="color:#0000CC;"><span style=""><a href="http://www.seniorliving.com/"><span style="text-decoration:none;"><span style="">http://www.ShepherdCares.com</span></span></a></span></span><span style="">&nbsp;(this &ldquo;</span><span style="">Site</span><span style="">&rdquo;). This Site is owned and operated by The Shepherd Company, LLC This Statement discloses the Privacy Policy (&ldquo;Policy&rdquo;) for the ShepherdCares.com Site. The Shepherd Company, LLC has created this Policy in order to demonstrate and inform you of our firm commitment to privacy. The following Policy describes how we collect, protect and use information we receive from visitors to our Site. This Policy applies only to information collected through this Site and not to information collected offline.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">THE INFORMATION WE COLLECT</span></strong></p>
                <p style=''><span style="">There are two kinds of information web sites can obtain about you:</span></p>
                <p style=''><span style="">(1) <em>Anonymous Information</em>: &ldquo;Anonymous Information&rdquo; is aggregate data that web sites use to administer their sites. It may include such information as your browser type or your Internet Protocol (IP) address. The Shepherd Company, LLC may from time to time retain third parties to help us collect and aggregate this Anonymous Information.</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><strong><span style="">IP Addresses.</span></strong><span style="">&nbsp;An IP address is a unique string of numbers that is assigned to your computer by your Internet Service Provider. Web servers automatically identify your computer by its IP address. We use your IP address to help diagnose problems with our server, to administer our Site, to avoid hacking attacks on the Site&rsquo;s server, and may use it to gather broad demographic information. Log data is only used in aggregate to analyze usage of this Site. We do not link IP addresses to any personally identifiable information, even if such information is voluntarily provided by a user.</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><strong><span style="">Cookie Information.</span></strong><span style="">&nbsp;As is the case with many web sites, our Site uses a technology called &ldquo;cookies,&rdquo; which are small data files that are downloaded onto your computer. The use of cookies is standard on the Internet, and allows us to tailor your visits to our Site to your individual preferences. We may also contract with third party service providers who assign cookies to conduct site tracking for us. These companies use cookies solely to provide us with aggregate data about site traffic. Although most web browsers automatically accept cookies, you can change your browser to prevent cookies or notify you whenever you are sent a cookie.</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><span style="">(2) <em>Personally Identifiable Information</em>: &ldquo;Personally Identifiable Information&rdquo; is any information that personally identifies you, such as your name, email address or your telephone number. Sometimes this personal information is needed when you contact us. We may ask you to provide us with personal information on a voluntary basis in certain areas of our Site. In particular, you may be asked to provide the following information:</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><strong><span style="">User IDs and Passwords.</span></strong><span style="">&nbsp;We may request that you create a login name and password. We may also use this information to send you announcements of new Site features and promotional material that we think may be of interest to you.</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><strong><span style="">Email Correspondence.</span></strong><span style="">&nbsp;Scattered throughout the Site are links or forms that can be used to contact The Shepherd Company, LLC so you can comment, make a complaint, make suggestions and ask questions. Your email address is required on this form so we can answer your questions. The Shepherd Company, LLC may put information from email on file, but does not currently share, sell, license or transmit this information with third parties without express authorization from you.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">HOW WE USE GATHERED INFORMATION</span></strong></p>
                <p style=''><span style="">The information you share with us may be used in a few ways:</span></p>
                <p style=''><span style="">(1) <em>Anonymous Information</em>: Anonymous Information is used internally for Site administration, troubleshooting and to help improve the quality of the Site. We may share such aggregated, non-personally identifiable information, such as demographics, with existing and prospective business partners and affiliates. We never connect aggregate information with Personally Identifiable Information, and none of the aggregate information we share will contain any information that identifies you individually.</span></p>
                <p style=''><span style="">(2) <em>Personally Identifiable Information</em>: Personally Identifiable Information collected by The Shepherd Company, LLC may be used for purposes including administration of the Site and communications with you. We may use this information to help us determine other products and services we may offer. We do not share this information with outside parties except in aggregate form. In all cases, we will use your information only as permitted by law.</span></p>
                <p style=''><span style="">We may also disclose Personally Identifiable Information if we are required to do so by law or we in good faith believe that such action is necessary to (a) comply with the law or with legal process; (b) protect and defend our rights and property; (c) protect against misuse or unauthorized use of the Site; or (d) protect the personal safety or property of our users or the public. Please note that we may not provide you with notice prior to disclosure in such cases.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">OPT-OUT</span></strong></p>
                <p style=''><span style="">Although most ShepherdCares.com users indicate that they welcome promotional material about ShepherdCares.com, we support the right of our visitors to choose. You will be given the right to opt-out of receiving such information whenever you are asked to provide Personally Identifiable Information on this Site. If you do not opt-out at that time, but later decide that you do not wish to receive future communications of this nature you can contact us at the address provided below, indicating that you no longer want to receive information relating to the ShepherdCares Site.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">ACCESS AND CORRECTION</span></strong></p>
                <p style=''><span style="">You have a right to know about the personal information that The Shepherd Company, LLC holds about you, including the right to correct, amend or delete the information that The Shepherd Company, LLC has on file if it is incorrect. If you wish to exercise these rights, please contact us by email or postal mail at the addresses below.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">DATA SECURITY</span></strong></p>
                <p style=''><span style="">This Site incorporates safeguards to protect the security, integrity and privacy of the personal information we have collected. We have put in place reasonable precautions to protect information from loss, misuse and alteration, including Secure Socket Layer (&ldquo;SSL&rdquo;) technology and database encryption. While on a secure page, the lock icon on the bottom of Web browsers such as Microsoft Internet Explorer and Mozilla Firefox becomes locked, as opposed to unlocked, or open, when you are just &ldquo;surfing.&rdquo; While we use SSL encryption to protect sensitive information online, we use reasonable efforts to protect user information offline. Our security and privacy policies are periodically reviewed and enhanced as required and only authorized individuals have access to the information you provide.</span></p>
                <p style=''><span style="">Security of information communicated by or to us over the Internet is of utmost concern to us; however, no data transmission over the Internet can be guaranteed to be 100% secure. Please note that your email, like most, if not all, non-encrypted Internet communications, may be accessed and viewed by other Internet users, without your knowledge and permission, while in transit to us. For that reason, to protect your privacy, please do not use email to communicate information to us that you consider confidential. While we strive to protect your personal information, The Shepherd Company, LLC cannot ensure or warrant the security of any information you transmit to us or through our Site, and you do so at your own risk. Once we receive your transmission, we will use reasonable efforts to ensure its security on our internal systems. Depending on the nature of the inquiry, your communication may be discarded or archived. If you wish, you may contact us instead via telephone at the numbers provided throughout our Site.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">DISCLOSURE OF INFORMATION THROUGH BUSINESS TRANSFERS</span></strong></p>
                <p style=''><span style="">As we continue to develop our business, we may buy, merge or partner with other companies or businesses, and in so doing, acquire or provide user information. In such transactions, user information may be among the transferred assets. Similarly, in the unlikely event that a portion or substantially all of The Shepherd Company, LLC&rsquo;s assets are sold or transferred to a third party, user information (including your email address) would likely be one of the transferred business assets.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">OUR COMMITMENT TO CHILDREN&apos;S PRIVACY</span></strong></p>
                <p style=''><span style="">Protecting the privacy of children is very important to us. The Children&apos;s Online Privacy and Protection Act of 1998 (&quot;COPPA&quot;) defines a &quot;Child&quot; as anyone under the age of 13. The Shepherd Company, LLC strictly adheres to COPPA. For that reason, we do not collect or maintain information obtained through our Site from those we actually know are under 13, and no part of our Site is structured to attract anyone under 13.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">EXTERNAL LINKS</span></strong></p>
                <p style=''><span style="">This Site may provide links and/or ad banners to various web sites or sponsors that we do not control. When you click on one of these links, you will be transferred out of our Site and connected to the web site of the organization or company that you selected. We are not responsible for the nature, quality or accuracy of the content or opinions expressed in such web sites, and such web sites are not investigated, monitored or checked for quality, accuracy or completeness by us. Inclusion of any linked web site on the ShepherdCares.com Site does not imply or express an approval or endorsement of the linked web site by us, or of any of the content, opinions, products or services provided on these web sites. Even if an affiliation exists between our Site and a third-party web site, we exercise no control over linked sites. Each of these linked sites maintains its own independent privacy and data collection policies and procedures. While&nbsp;The Shepherd Company, LLC expects its partners and affiliates to respect the privacy of our users, The Shepherd Company, LLC cannot be responsible for the actions of third parties. If you visit a web site that is linked to our Site, we encourage you to consult that web site&apos;s privacy policy before providing any personal information and whenever interacting with any web site.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">OPERATION OF OUR SERVICES IN THE UNITED STATES</span></strong></p>
                <p style=''><span style="">Our Services are operated in the United States. If you are located in the European Union, Canada or elsewhere outside of the United States, please be aware that any information you provide to us will be transferred to the United States. By using our Services or providing us with Your Information, you consent to this transfer.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">CONSENT AND MODIFICATIONS TO PRIVACY STATEMENT</span></strong></p>
                <p style=''><span style="">This Site is controlled, operated and administered entirely within the United States. By using this Site, you signify your agreement to the terms of our Privacy Policy. If you do not agree with this Policy, please do not disclose any personal information through this Site. This Policy and the use of this Site are governed by Tennessee law. ANY CLAIM RELATED TO THE SITE OR THIS POLICY SHALL BE BROUGHT IN A FEDERAL OR STATE COURT IN DAVIDSON COUNTY, NASHVILLE, TENNESSEE, WITHIN ONE YEAR AFTER THE CLAIM ARISES. USERS OF THE SITE CONSENT TO THE EXCLUSIVE JURISDICTION AND VENUE OF SUCH COURTS AS THE MOST CONVENIENT AND APPROPRIATE FOR THE RESOLUTION OF DISPUTES CONCERNING THIS POLICY. This Policy and the notices outlined herein are not intended to and do not create any contractual or other legal rights in or on behalf of any third party.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">SPECIAL NOTICE TO CALIFORNIA RESIDENTS</span></strong></p>
                <p style=''><span style="">Under the California Civil Code, residents of the State of California that have provided any Personally Identifiable Information to ShepherdCares.com have the right to request a list of all third parties to which ShepherdCares.com has disclosed Personally Identifiable Information during the preceding year for direct marketing purposes. Alternatively, the law provides that if ShepherdCares.com has a privacy policy that gives either an opt-out or opt-in choice for use of Personally Identifiable Information by third parties (such as advertisers or affiliated companies) for marketing purposes, ShepherdCares.com may instead provide you with information on how to exercise your disclosure choice options free of charge. ShepherdCares.com qualifies for the alternative option and has adopted a policy of not disclosing the personal information of customers to third parties for the third parties&apos; direct marketing purposes if the customer has exercised an option that prevents that information from being disclosed to third parties for those purposes. It has established this Policy that provides you with details on how you may either opt-out of the use of your Personally Identifiable Information by third parties for direct marketing purposes. If you are a California resident and would like to request information about how to exercise your third party disclosure choices, please send a request to&nbsp;</span><span style="color:#0000CC;"><span style=""><a href="mailto:info@seniorliving.com"><span style="text-decoration:none;"><span style="">info@ShepherdCares.com</span></span></a></span></span><span style="">&nbsp;with a preference on how our response to your request should be sent.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">MODIFICATIONS TO PRIVACY POLICY</span></strong></p>
                <p style=''><span style="">The Shepherd Company, LLC may modify this Policy at any time, at its discretion and without notice to you, and modifications are effective upon being posted on this Site. You are responsible for reviewing this Policy periodically to ensure that you are aware of any changes to it.</span></p>
                <p style=''><strong><span style="">&nbsp;</span></strong></p>
                <p style=''><strong><span style="">ACCOUNT REVISIONS, REVOKING AND DELETING PERSONAL INFORMATION</span></strong></p>
                <p style=''><span style="">We welcome your questions, comments and all feedback pertaining to your privacy or any other issue regarding this Site.</span></p>
                <p style=''><span style="">At any time, you may ask us to cease further use of your email address to send you updates. Although it is not always possible to remove or modify such information from our databases, we will make reasonable efforts to do so. If you have given us information and we have already passed that information on to a third party in accordance with this Policy, we cannot delete or change the information.</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><span style="">For any questions concerning this Site or ShepherdCares.com, please contact us at:</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><span style="">The Shepherd Company, LLC</span></p>
                <p style=''><span style="">2020 Fieldstone Parkway</span></p>
                <p style=''><span style="">Suite 900-260</span></p>
                <p style=''><span style="">Franklin, TN 37069</span></p>
                <p style=''><span style="">&nbsp;</span></p>
                <p style=''><span style="">Thank you.</span></p>
                <p style=''><em><span style="">This Policy was last updated and is effective as of August 1, 2021</span></em></p>
            </div>
            
        </div>
    </div>
    
</div>
@endsection

@push('styles')
<style>

    
</style>
@endpush
