@extends('layouts.app_simple')

@section('content')
<div id="home">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 mb-4">

                <h3 class="mb-5">ShepherdCares.com Terms of Use</h3>
                
                <p style=''><span >Welcome to the ShepherdCares.com web site (this &ldquo;</span><span >Site</span><span >&rdquo;). This Site is owned and operated by The Shepherd Company, LLC. Please read this Agreement carefully before using this Site. By accessing or using this Site in any way, including without limitation, browsing this Site, using any information, and/or submitting any content or your personal information to The Shepherd Company, LLC, you agree to and are bound by the terms, conditions, policies and notices contained on this page (these &ldquo;Terms&rdquo;), including, but not limited to, conducting this transaction electronically, disclaimers of warranties, damage and remedy exclusions and limitations, and a choice of Tennessee law.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >&nbsp;</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >1. Site Content</span></strong></p>
                <ul style="list-style-type: undefined;margin-left:26px;">
                    <li><span >All contents of this Site are:&nbsp;</span><span >&copy;</span><span >The Shepherd Company, LLC All rights reserved. ShepherdCares and the ShepherdCares logo and all other logos, trademarks and service marks contained on this Site are registered trademarks of The Shepherd Company, LLC This Site contains copyrighted material, trademarks, service marks, trade dress and other proprietary content, including but not limited to text, software, sound, photographs, buttons, images, logos, video and graphics (the &ldquo;</span><span >Content</span><span >&rdquo;), and the entire selection, coordination, arrangement and &ldquo;look and feel&rdquo; of this Site and the Content are copyrighted as a collective work under United States copyright laws (collectively, &ldquo;Intellectual Property Rights&rdquo;). You are only permitted to use Content as expressly authorized herein or in writing by The Shepherd Company, LLC Neither these Terms nor your use of this Site transfers any right, title or interest in the Site or the Content to you, and The Shepherd Company, LLC retains all of its right, title and interest to the Site and Content.</span></li>
                    <li><span >Except as provided in these Terms, you may not use, modify, republish, frame, print, display, perform, reproduce, license, transfer, sell, assign, post, transmit, distribute, reverse engineer, create derivative works from, or otherwise exploit any Content or information from this Site, in whole or in part, without the express permission of The Shepherd Company, LLC In addition, you agree not to use any data mining, robots, or similar data gathering and extraction methods in connection with this Site.</span></li>
                    <li><span >This Site is available worldwide to anyone with Internet access. However, this Site may not be continuously available due to maintenance or repairs or due to computer problems or crashes, disruption in Internet service or other unforeseen circumstances. Further, a reference to a product or service on this Site does not imply that such product or service is or will be available in your location. The content of this Site, including advertising content, is intended for use and display only where its use and display are permissible in accordance with applicable laws and regulations.</span></li>
                    <li><span >Certain materials on this Site may be furnished by third parties. Certain product, service, or company designations for companies other than The Shepherd Company, LLC may be mentioned in the Site for identification purposes only. Third-party trademarks, trade names, logos, product or services names contained on this Site are the trademarks, registered or unregistered, of their respective owners.</span></li>
                    <li><span >Nothing contained in these Terms shall be construed as conferring any other license or right, expressly, by implication, by estoppel or otherwise, under any of our Intellectual Property Rights or under any third party&apos;s Intellectual Property Rights. Any rights not expressly granted herein are reserved.</span></li>
                </ul>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >2. Permissible Use</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >Except as indicated to the contrary elsewhere on this Site, you may view, copy, retransmit and print the Content available on this Site subject to the following conditions:</span></p>
                <ul style="list-style-type: undefined;margin-left:26px;">
                    <li><span >The Content is used solely for personal, informational, or internal business purposes;</span></li>
                    <li><span >the Content is not provided, sold, licensed or leased (nor is access provided to the Content) for any fee or other consideration;</span></li>
                    <li><span >all copyright, trademark and other proprietary rights notices included in the Content as presented on this Site appear on all copies;</span></li>
                    <li><span >the Content is not modified or altered in any way; and</span></li>
                    <li><span >no graphics are used separately from accompanying text.</span></li>
                </ul>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >3. User Conduct</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >In using the Site, including all Content and services available through it, you agree that you shall not:</span></p>
                <ul style="list-style-type: undefined;margin-left:26px;">
                    <li><span >delete, modify, hack or attempt to change or alter any of the Content on the Site;</span></li>
                    <li><span >use any device, software or routine intended to damage or otherwise interfere with the proper functioning of the Site or servers or networks connected to the Site, or take any other action that interferes with other parties&apos; use of the Site;</span></li>
                    <li><span >use any robot, spider or other automatic or manual device or process for the purpose of harvesting or compiling information on the Site for purposes other than for a generally available search engine;</span></li>
                    <li><span >use any The Shepherd Company, LLC names, service marks, or trademarks without our prior written consent, including without limitation as metatags, search engine keywords, or hidden text;</span></li>
                    <li><span >use or transmit any material or information, including images or photographs, which are made available through this Site in any manner that infringes any copyright, trademark, patent, trade secret or other proprietary right of any party;</span></li>
                    <li><span >upload or transmit files that contain viruses, Trojan horses, worms, time bombs, cancelbots, corrupted files, or any other similar software or programs that may damage the operation of another&apos;s computer or property of another;</span></li>
                    <li><span >create a false identity for the purpose of misleading others;</span></li>
                    <li><span >publish, post, upload, distribute or disseminate any inappropriate, profane, obscene, indecent or unlawful topic, name, material or information; or</span></li>
                    <li><span >defame, abuse, harass, stalk, threaten or otherwise violate the legal or privacy rights of any third party.</span></li>
                </ul>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >The Shepherd Company, LLC has no obligation to monitor any bulletin board services, chat areas, blogs or other forums on this Site. However, The Shepherd Company, LLC reserves the right to review materials posted to these common areas and to remove any materials in its sole discretion.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >4. Modifications To Terms</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >The Shepherd Company, LLC may change these Terms from time to time. Please review these Terms periodically for any updates or changes. Your continued use of this Site following the posting of any updates or changes to these Terms constitutes your acceptance of such changes. If you object to any provision of these Terms or any subsequent modifications to these Terms, your only recourse is to immediately terminate use of the Site.&nbsp;</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >5. Termination of Site/Modifications To Site</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >The Shepherd Company, LLC reserves the right to modify or terminate your access to the Site (or portions of the Site) at any time, temporarily or permanently, with or without notice to you, and is not obligated to support or update the Site. Sections 1, 4, this Section 5, and 9-18 of these Terms shall survive any termination of these Terms.&nbsp;The Shepherd Company, LLC may also impose limits on certain features and services, restrict your access to parts or all of this Site, or charge fees for access to portions of this Site without notice or liability. You acknowledge and agree that The Shepherd Company, LLC will not be liable to you or any third party in the event that The Shepherd Company, LLC exercises its right to modify or terminate access to the Site or portions of the Site.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >6. Your Privacy</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >The Shepherd Company, LLC will treat any information it collects from you through this Site in accordance with its web site Privacy Policy (the &ldquo;Privacy Policy&rdquo;), which is hereby incorporated by reference. Please review the Privacy Policy before you use this Site. If you are unwilling to accept the terms and conditions of the Privacy Policy, please exit this Site immediately.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >7. Accounts and Passwords</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >In order to access certain features on this Site, you may be required to create an account. By setting up an account, you agree to provide The Shepherd Company, LLC with accurate and complete information. You are responsible for protecting and maintaining the secrecy of your username and password. The Shepherd Company, LLC will not be responsible or liable for any loss or damage that result from your failure to comply with this security obligation. You are solely responsible for any and all activities or actions that occur under your account, whether or not you have authorized such activities or actions. You agree to immediately notify The Shepherd Company, LLC of an unauthorized use of your username or password.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >8. Copyright Infringement</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >In accordance with the Digital Millennium Copyright Act (&quot;DMCA&quot;), The Shepherd Company, LLC has designated an agent to receive notifications of alleged copyright infringement associated with the Site. The Shepherd Company, LLC will, upon receiving proper notice as set forth below, use commercially reasonable efforts to investigate notices of copyright infringement and take appropriate action under the DMCA. If you believe that your copyrighted work or the copyrighted work of another party is being infringed, please notify our copyright agent at&nbsp;</span><span style="color:#0000CC;font-weight:bold;"><span style="color:black;"><a href="mailto:admin@SeniorLiving.com"><span style="font-size:21px;color:black;font-weight:normal;text-decoration:none;"><span style="color:black;">admin@ShepherdCares.com</span></span></a></span></span><span >&nbsp;or through the address set forth at the end of this page. When notifying The Shepherd Company, LLC of the alleged copyright infringement, please include all of the following information:</span></p>
                <ul style="list-style-type: undefined;margin-left:26px;">
                    <li><span >A physical or electronic signature of a person authorized to act on behalf of the owner of the copyright interest that is claimed to have been infringed;</span></li>
                    <li><span >identification of the copyrighted work alleged to have been infringed;</span></li>
                    <li><span >a description of the material that is claimed to be infringing and information sufficient to locate the material on the Site;</span></li>
                    <li><span >information sufficient to contact the complaining party, such as a physical address, telephone number, and, if available, an electronic mail address;</span></li>
                    <li><span >a statement that the complaining party has a good faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</span></li>
                    <li><span >a statement that the information in the notification is accurate and, under penalty of perjury, that the complaining party is authorized to act on the copyright owner&rsquo;</span><span style="font-size:21px;color:#333333;color:#333333;">s behalf.</span></li>
                </ul>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >If material is believed in good faith by The Shepherd Company, LLC to infringe a copyright or otherwise violate any Intellectual Property Rights, The Shepherd Company, LLC will remove or disable access to any such material.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >9. Other Sites, Content, Products and Services</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >As a convenience to you, this Site may provide links to web sites and access to content, products and services of third parties, including without limitation, The Shepherd Company, LLC&rsquo;s affiliates, advertisers and strategic partners and other entities with which our connection consists of only a hyperlink (&ldquo;Linked Sites&rdquo;). You should refer to the separate terms of use, privacy policies, and other rules posted on Linked Sites before you use them. The Shepherd Company, LLC does not author, edit or monitor these Linked Sites, and is not responsible or liable for (a) the availability of or content provided on such Linked Sites, nor does inclusion of any link imply endorsement of the Linked Sites by The Shepherd Company, LLC, or vice versa; (b) third party content accessible through such Linked Sites; (c) any loss or damage whatsoever you may incur from dealing with any Linked Site; or (d) your dealings with any third parties found on or through this Site.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >10. Typographical Errors</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >Our goal is to provide complete, accurate, up-to-date information on our Site. Unfortunately, it is not possible to ensure that any web site is completely free of human or technological errors. This Site may contain typographical mistakes, inaccuracies, or omissions, and some information may not be complete or current. The Shepherd Company, LLC therefore reserves the right to correct any errors, inaccuracies or omissions and to change or update information at any time without prior notice.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >11. Disclaimer</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, THIS SITE AND ALL CONTENT, MATERIALS, INFORMATION, PRODUCTS AND SERVICES PROVIDED ON THIS SITE, ARE PROVIDED ON AN &quot;AS IS, WHERE IS&quot; AND &quot;AS AVAILABLE&quot; BASIS, WITH ALL FAULTS. The Shepherd Company, LLC EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, QUIET ENJOYMENT, AND SECURITY AND ACCURACY, AS WELL AS ALL WARRANTIES ARISING BY USAGE OF TRADE, COURSE OF DEALING, OR COURSE OF PERFORMANCE. The Shepherd Company, LLC MAKES NO WARRANTY, AND EXPRESSLY DISCLAIMS ANY OBLIGATION, THAT: (A) THE SITE WILL MEET YOUR REQUIREMENTS OR WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; (B) THE CONTENT OR ANY SUBMISSION WILL BE UP-TO-DATE, COMPLETE, COMPREHENSIVE OR ACCURATE; (C) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SITE OR ANY SERVICES OFFERED THROUGH THE SITE WILL BE ACCURATE OR RELIABLE; (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL OBTAINED BY YOU THROUGH THE SITE WILL MEET YOUR EXPECTATIONS; OR (E) THAT DEFECTS, IF ANY, WILL BE CORRECTED.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >12. Limitation of Liability</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >IN NO EVENT SHALL The Shepherd Company, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, INCREASED OR CONSEQUENTIAL DAMAGES, LOSS OF PROFITS, REVENUE, DATA, GOODWILL OR USE, INCURRED BY YOU OR ANY THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT (INCLUDING NEGLIGENCE AND STRICT LIABILITY), ARISING FROM YOUR ACCESS TO OR INABILITY TO ACCESS, OR USE OF, THIS SITE OR ANY SERVICES PROVIDED IN CONNECTION WITH THIS SITE, OR OTHERWISE RESULTING FROM: (A) THE COST OF PROCUREMENT OF SUBSTITUTE SERVICES OR GOODS, (B) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, OR (C) ANY OTHER MATTER RELATING TO THIS SITE, EVEN IF The Shepherd Company, LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS OR EXCLUSIONS OF LIABILITY IN SOME CIRCUMSTANCES. CONSEQUENTLY, SOME OF THE FOREGOING LIMITATIONS MAY NOT APPLY TO YOU. IF THE LIMITATIONS SET FORTH IN THIS SECTION 12 ARE HELD TO BE UNENFORCEABLE FOR ANY REASON, The Shepherd Company</span><span >, LLC</span><span >&rsquo;S LIABILITY FOR ANY TYPE OF DAMAGES SHALL NOT EXCEED ONE HUNDRED DOLLARS.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >13. Indemnity</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >You agree to indemnify, defend and hold The Shepherd Company, LLC, its affiliates, shareholders, directors, officers, co-branders, subsidiaries, parents, employees and agents, harmless from any claim, demand, liability, dispute, damage, cost, expense, or loss, including attorneys&apos; fees and costs of litigation, arising out of or in any way related to your use of or access to this Site, your use of the Content, including any use by your employees, your violation of these Terms or your violation of any rights of another.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >14. Limitation on Actions Brought Against&nbsp;The Shepherd Company, LLC</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >You agree that any claim or cause of action arising out of your use of this Site or these Terms must be filed within one year after such claim or cause of action arose or it shall forever be barred, notwithstanding any statute of limitations or other law to the contrary. Within this period, any failure by The Shepherd Company, LLC to enforce or exercise any provision of these Terms or related right shall not constitute a waiver of that right or provision.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >15. Dispute Resolution</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >You agree that any dispute arising out of or relating in any way to your use of this Site requires that such claim be resolved exclusively by confidential binding arbitration except that, to the extent you have in any manner violated or threatened to violate Intellectual Property Rights, The Shepherd Company, LLC may seek injunctive or other appropriate relief. The arbitration shall be conducted before three neutral arbitrators in the City of Nashville, Tennessee, U.S.A., in accordance with the rules of the American Arbitration Association (&quot;AAA&quot;), as then in effect. No claims of any other parties may be joined or otherwise combined in the arbitration proceeding. Unless otherwise expressly required by applicable law, each party shall bear its own attorneys&apos; fees without regard to which party is deemed the prevailing party in the arbitration proceeding. Except for punitive and consequential damages (which may not be awarded), and subject to these Terms, the arbitrators shall be authorized to award either party any provisional or equitable remedy permitted by applicable law. The parties shall equally share all AAA charges and fees associated with the arbitration.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >BECAUSE THE USE OF THIS SITE REQUIRES THE ARBITRATION OF ANY CLAIMS OR DISPUTES EXISTING BETWEEN THE PARTIES, NEITHER PARTY WILL HAVE THE RIGHT TO PURSUE THAT CLAIM IN COURT OR BEFORE A JUDGE OR JURY OR TO PARTICIPATE IN A CLASS ACTION OR ANY OTHER COLLECTIVE OR REPRESENTATIVE PROCEEDING. THE ARBITRATORS&apos; DECISION WILL BE FINAL AND BINDING. OTHER RIGHTS THAT EITHER PARTY WOULD HAVE IF SUCH PARTY WENT TO COURT, INCLUDING WITHOUT LIMITATION THE RIGHT TO CONDUCT DISCOVERY OR TO APPEAL, MAY BE LIMITED OR UNAVAILABLE IN ARBITRATION.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >The award of the arbitrators may be enforced in any court having jurisdiction thereof. Each party hereby consents (a) to the non-exclusive jurisdiction of the courts of the State of Tennessee or to any Federal Court located within the State of Tennessee for any action (i) to compel arbitration, (ii) to enforce any award of the arbitrators, or (iii) at any time prior to the qualification and appointment of the arbitrators, for temporary, interim or provisional equitable remedies, and (b) to service of process in any such action by registered mail or any other means provided by law. Should this Section 15 be deemed invalid or otherwise unenforceable for any reason, it shall be severed and the parties agree that exclusive jurisdiction and venue for any claims will be in state or federal courts in Nashville, Tennessee.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >16. Acknowledgement</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >You acknowledge (a) that you have read and understood these Terms; and (b) that these Terms have the same force and effect as a signed agreement.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >&nbsp;</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >17. General</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >If any provision of these Terms is found by a court or arbitrator to be invalid, the parties agree that the court or arbitrator should give effect to the parties&apos; intentions as reflected in the provision, and the other provisions of these Terms will remain in full force and effect. The Shepherd Company, LLC&apos;s failure to act with respect to a breach by any visitor using the Site does not constitute a waiver of its right to act with respect to subsequent or similar breaches. These Terms will be governed by and construed in accordance with the laws of the State of Tennessee without regard to its choice of law provisions. In the event of any conflict between foreign laws, rules and regulations and those of the United States, the laws, rules and regulations of the United States will govern. These Terms and the Privacy Policy as posted from time to time by The Shepherd Company, LLC on this Site, and any modifications to the foregoing, constitute the entire agreement between the parties with regard to the subject matter in these Terms and supersede all prior understandings and agreements, whether written or oral, as to such subject matter.</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><strong><span >18. Contact Information</span></strong></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >If you have any questions about these Terms, the practices of The Shepherd Company, LLC, or your dealings with this Site, please contact us through the address below. You may also contact us to update your personal information by notifying us when you change your name or email address.</span></p>
                <p><span style='font-size:21px;font-family:"Arial Unicode MS",sans-serif;color:#333333;'><br>&nbsp;</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'>&nbsp;</p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >Address:</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >The Shepherd Company, LLC</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >2020 Fieldstone Parkway</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >Suite 900-260</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><span >Franklin, TN 37069</span></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><em><span >&nbsp;</span></em></p>
                <p style='margin:0cm;font-size:15px;font-family:"Helvetica Neue";color:black;border:none;'><em><span >Last updated and effective: August 1, 2021</span></em></p>
            </div>
            
        </div>
    </div>
    
</div>
@endsection

@push('styles')
<style>

    
</style>
@endpush
